// clang-format off
// This file is autogenerated from Lib/ST01_Central_Station.json

#include "space_station_desc.hpp"

SpaceStationDesc GetST01CentralStationDesc() {
  return SpaceStationDesc{
    .pos{-119.2f, -562.8f},
    .name{"Central Station"},
    .desc{"Guten Tag, Hola, Hello! Welcome to Central!\nTravellers, businessmen and diplomats just love coming here.\nFeel at home and make sure to visit once in a while.\nRemember: Central is THE place."},
    .jump_distance = 1800,
    .difficulty_str{"moderate"},
    .difficulty = 0,
    .asteroids{
      {
        .pos{-304.0f, -88.8f},
        .radius = 10.0f,
      },
      {
        .pos{-38.0f, -22.8f},
        .radius = 10.0f,
      },
      {
        .pos{56.0f, -110.8f},
        .radius = 10.0f,
      },
      {
        .pos{50.0f, 74.2f},
        .radius = 10.0f,
      },
      {
        .pos{292.6f, -302.7f},
        .radius = 10.0f,
      },
      {
        .pos{462.4f, 517.3f},
        .radius = 10.0f,
      },
      {
        .pos{-625.0f, 430.6f},
        .radius = 10.0f,
      },
      {
        .pos{-534.7f, -501.4f},
        .radius = 10.0f,
      },
    }
  };
}
// clang-format on
