// clang-format off
// This file is autogenerated from Lib/ST01_Central_Station.json

#include "space_station_desc.hpp"

SpaceStationDesc GetST01CentralStationDesc() {
  return SpaceStationDesc{
    .name{"Central Station"},
    .desc{"Guten Tag, Hola, Hello! Welcome to Central!\nTravellers, businessmen and diplomats just love coming here.\nFeel at home and make sure to visit once in a while.\nRemember: Central is THE place."},
    .pos{-119.21569567246287, -562.8312980824467},
    .difficulty = 0,
    .difficulty_str{"moderate"},
    .jump_distance = 1800,
    .asteroids{
      {
        .pos{-304, -88.796875},
        .radius = 10,
      },
      {
        .pos{-38, -22.796875},
        .radius = 10,
      },
      {
        .pos{56, -110.796875},
        .radius = 10,
      },
      {
        .pos{50, 74.203125},
        .radius = 10,
      },
      {
        .pos{292.62034392331793, -302.724325706164},
        .radius = 10,
      },
      {
        .pos{462.41239533561355, 517.3351566468382},
        .radius = 10,
      },
      {
        .pos{-624.9792530707902, 430.63283252141065},
        .radius = 10,
      },
      {
        .pos{-534.6643321068032, -501.4171518269355},
        .radius = 10,
      },
    }
  };
}
// clang-format on
